DROP TABLE IF EXISTS GAME_INFO;
DROP SEQUENCE IF EXISTS GAME_INFO_SEQ;

CREATE SEQUENCE GAME_INFO_SEQ START WITH 1 INCREMENT BY 1 NO MINVALUE  NO MAXVALUE CACHE 1;

CREATE TABLE GAME_INFO (
    ID INTEGER NOT NULL,
    APP_ID BIGINT,
    GAME_CATEGORY CHARACTER VARYING (256),
    BUY_DATE CHARACTER VARYING (256),
    GAME_DESCRIPTION TEXT,
    ALREADY_PLAYED BOOLEAN,
    UPDATE_TIME BIGINT
);

ALTER SEQUENCE GAME_INFO_SEQ OWNER TO DAN;
ALTER TABLE GAME_INFO OWNER TO DAN;

ALTER SEQUENCE GAME_INFO_SEQ OWNED BY GAME_INFO.ID;
ALTER TABLE ONLY GAME_INFO ALTER COLUMN ID SET DEFAULT NEXTVAL('GAME_INFO_SEQ'::REGCLASS);

ALTER TABLE ONLY GAME_INFO ADD CONSTRAINT GAME_INFO_PRIMARY_KEY_ID_CONSTRAINT PRIMARY KEY (ID);
ALTER TABLE ONLY GAME_INFO ADD CONSTRAINT GAME_INFO_UNIQUE_KEY_SUB_ID_CONSTRAINT UNIQUE (APP_ID);

COMMENT ON COLUMN GAME_INFO.ID IS '游戏于数据库中的标识ID';
COMMENT ON COLUMN GAME_INFO.APP_ID IS '游戏于STEAM的标识ID';
COMMENT ON COLUMN GAME_INFO.GAME_CATEGORY IS '游戏的分类，枚举值，需要预定义';
COMMENT ON COLUMN GAME_INFO.BUY_DATE IS '购买时间，格式限定为2000-01-01，字符串型来避免时区问题';
COMMENT ON COLUMN GAME_INFO.GAME_DESCRIPTION IS '游戏描述，自撰写';
COMMENT ON COLUMN GAME_INFO.ALREADY_PLAYED IS '是否已经游玩过了';
COMMENT ON COLUMN GAME_INFO.UPDATE_TIME IS '这些数据的更新时间，UTC时间，ms级';
